### PR TITLE
Co 388 swagger

### PR DESCRIPTION
**Pull request by floppyears**

### CODE REVIEW

**Comment by floppyears** [comment]
What would be a sample piece of data if I call: /slash_courses?all=foobar ? I think the current schema only allows one course to be returned.

The GET, DELETE and PUT /slash_coures/crn/{crn} should be: /slash_coures/{crn} because crn is the id that you are using for your courses. 

Your GET /slash_courses specifies a schema for the non-200 responses, but the other api endpoints, don't. 

I would remove the endpoints that use: /slash_courses/course_num/ . You should be able to add a new filter / parameter to /slash_courses to search courses based on the course_num.

**Comment by floppyears** [comment]
I'm not sure that it makes sense for DELETE /slash_coures/{crn} to return the json object when there's a 200 return code. Technically the object / data is gone.

**Comment by tsoliangwu0130** [comment]
Hmm... what I thought was showing the object information which was just deleted. Did I misunderstand the meaning?

**Comment by floppyears** [comment]
If your DELETE resource returns the object just deleted, your operation may not be idempotent. Both PUT and DELETE are operations that are idempotent. In other words, if you call PUT or DELETE a thousand times with the same parameters the result is the same and could be considered a safe operation to re-try.

**Comment by floppyears** [comment]
Your GET /slash_courses returns a single json object. You need to modify it so that it returns an array of objects.

**Comment by tsoliangwu0130** [comment]
Oh, I see. Thanks for the clarification, I will fix them tomorrow :)

**Pull request merged**
